"""
Permutation group utilities.
"""

from basicpermutationgroup import *


def order(generators):
    """
    Calculates the order of the permutation group generated by generators.
    :param generators: should be a Python list of permutations (from permv2.py),
            which represent a generating set of a permutation group H.
    :return: the order of the group
    """

    if len(generators) == 0:
        return 1

    el = FindNonTrivialOrbit(generators)

    if el is None:
        return 1

    el_orbit = Orbit(generators, el)
    el_stabilizer = Stabilizer(generators, el)

    return len(el_orbit) * order(el_stabilizer)


def is_member(perm, generators):
    """
    Checks if the given permutation is a member of the set generated by generators.
    :param perm: the permutation (from permv2.py) to check if it is a member
    :param generators: should be a Python list of permutations (from permv2.py),
            which represent a generating set of a permutation group H.
    :return: <True> iff permutation is a member of the set generated by generators
    """

    if perm in generators or perm.istrivial():
        return True
    elif len(generators) == 0:
        return False

    alpha = FindNonTrivialOrbit(generators)

    if alpha is None:
        return False

    alpha_orbit, alpha_traversal = Orbit(generators, alpha, True)
    alpha_stabilizer = Stabilizer(generators, alpha)
    beta = perm[alpha]
    return beta in alpha_orbit and is_member(-alpha_traversal[alpha_orbit.index(beta)]*perm, alpha_stabilizer)